spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qlthanhvien?createDatabaseIfNotExist=true
    username: root
    password: 123456789

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  thymeleaf:
    enabled: true
    check-template-location: true

server:
  port: 8888


